apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpfpm
      tier: backend
  template:
    metadata:
      labels:
        app: phpfpm
        tier: backend
    spec:
      volumes:
      - name: code
        persistentVolumeClaim: # Cloud Volume
          claimName: code
      containers:
      - name: php
        image: php:7.4-fpm
        volumeMounts:
        - name: code
          mountPath: /code
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: code
          mountPath: /code
        command:
        - wget
        - "-O"
        - "/code/index.php"
        - https://raw.githubusercontent.com/do-community/php-kubernetes/master/index.php
