apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  labels:
    app: hosting
    tier: database
spec:
  type: NodePort
  selector:
    name: mysql
  ports:
   - name: mysqlport
     port: 3306
     targetPort: 3306
     nodePort: 30336
     protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: hosting
    tier: database
spec:
  type: ClusterIP
  clusterIP: 10.152.183.136
  selector:
    name: mysql
  ports:
   - name: mysqlport
     port: 3306
     targetPort: 3306
     protocol: TCP
