apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: default
spec:
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      labels:
        app: hosting
        tier: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.27
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Secret1235
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      # Asigna el PVC que hara referencia al punto de montaje en el contenedor
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pv-data-claim
