apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: lab
    app: webserver
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 2
  template:
    metadata:
      labels:
        env: lab
        app: webserver
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: metrics
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.8.0
        ports:
        - containerPort: 9113
        args: ["-nginx.scrape-uri","http://localhost:8080/metrics"]
      volumes:
      - name: metrics
        configMap:
          name: nginx-metrics
