apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-data-pv
  namespace: test
  labels:
    type: local
spec:
  claimRef:
    name: prom-data-pvc
    namespace: test
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/srv/promethueus-fast/prometheus"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-data-pvc
  namespace: test
spec:
  volumeName: prom-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
