kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding
  namespace: live
subjects:
- kind: User
  name: user
  apiGroup: ""
roleRef:
  kind: Role
  name: role
  apiGroup: ""
