kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: NAMESPACE
  name: USER-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create", "port-forward"]
