apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nginxproxy-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx
      tier: backend
      
